os: osx
language: objective-c

before_install:
 - brew update
 - node --version
 - brew unlink node
 - brew install homebrew/versions/node4-lts
 # - brew install wine makensis
 - sudo gem install fpm
 - sudo npm install -g electron-builder electron-packager

install:
 - npm install --no-spin
 # - npm run dist:all
 - electron-packager . Wakenator --platform=darwin--arch=x64 --version=0.36.7 --overwrite --out=build --ignore='(psd|build)'
 - electron-packager . Wakenator --platform=linux --arch=x64 --version=0.36.7 --overwrite --out=build --ignore='(psd|build)'
 - electron-builder \"build/Wakenator-linux-x64\" --platform=linux --out=\"build\" --config=builder.json
 - electron-builder \"build/Wakenator-win32-x64\" --platform=win --out=\"build\" --config=builder.json
